var hierarchy =
[
    [ "AssetPostprocessor", null, [
      [ "ImagenImportProcessor", "class_imagen_import_processor.html", null ]
    ] ],
    [ "AnimatedButton.BlinkSettings", "class_animated_button_1_1_blink_settings.html", null ],
    [ "AnimatedButton.ColorSettings", "class_animated_button_1_1_color_settings.html", null ],
    [ "EditorWindow", null, [
      [ "AñadirPunto", "class_a_xC3_xB1adir_punto.html", null ],
      [ "BottonNavigationAsignerCont", "class_botton_navigation_asigner_cont.html", null ],
      [ "CursorChangerAsignerContent", "class_cursor_changer_asigner_content.html", null ]
    ] ],
    [ "AnimatedButton.FloatSettings", "class_animated_button_1_1_float_settings.html", null ],
    [ "IPointerClickHandler", null, [
      [ "CursorChanger", "class_cursor_changer.html", null ],
      [ "CursorChangerMenu", "class_cursor_changer_menu.html", null ],
      [ "LinkOpener", "class_link_opener.html", null ],
      [ "TMP_LinkOpener", "class_t_m_p___link_opener.html", null ]
    ] ],
    [ "IPointerEnterHandler", null, [
      [ "AnimatedButton", "class_animated_button.html", null ],
      [ "AnimatedButtonMenu", "class_animated_button_menu.html", null ],
      [ "BotonNavegacion", "class_boton_navegacion.html", null ],
      [ "ButtonHoverEffect", "class_button_hover_effect.html", null ],
      [ "CanvasTextSelected", "class_canvas_text_selected.html", null ],
      [ "CursorChanger", "class_cursor_changer.html", null ],
      [ "CursorChangerMenu", "class_cursor_changer_menu.html", null ],
      [ "HoverTextDisplay", "class_hover_text_display.html", null ],
      [ "MainTextSelected", "class_main_text_selected.html", null ],
      [ "MostrarSliderSonido", "class_mostrar_slider_sonido.html", null ],
      [ "ShowHandle", "class_show_handle.html", null ],
      [ "SimpleButtonHover", "class_simple_button_hover.html", null ],
      [ "StopMovementPanel", "class_stop_movement_panel.html", null ],
      [ "StopZoom", "class_stop_zoom.html", null ],
      [ "TransitionScrollBar", "class_transition_scroll_bar.html", null ]
    ] ],
    [ "IPointerExitHandler", null, [
      [ "AnimatedButton", "class_animated_button.html", null ],
      [ "AnimatedButtonMenu", "class_animated_button_menu.html", null ],
      [ "BotonNavegacion", "class_boton_navegacion.html", null ],
      [ "ButtonHoverEffect", "class_button_hover_effect.html", null ],
      [ "CanvasTextSelected", "class_canvas_text_selected.html", null ],
      [ "CursorChanger", "class_cursor_changer.html", null ],
      [ "CursorChangerMenu", "class_cursor_changer_menu.html", null ],
      [ "HoverTextDisplay", "class_hover_text_display.html", null ],
      [ "MainTextSelected", "class_main_text_selected.html", null ],
      [ "MostrarSliderSonido", "class_mostrar_slider_sonido.html", null ],
      [ "ShowHandle", "class_show_handle.html", null ],
      [ "SimpleButtonHover", "class_simple_button_hover.html", null ],
      [ "StopMovementPanel", "class_stop_movement_panel.html", null ],
      [ "StopZoom", "class_stop_zoom.html", null ],
      [ "TransitionScrollBar", "class_transition_scroll_bar.html", null ]
    ] ],
    [ "IScrollHandler", null, [
      [ "FastScrollRect", "class_fast_scroll_rect.html", null ]
    ] ],
    [ "MonoBehaviour", null, [
      [ "AnimatedButton", "class_animated_button.html", null ],
      [ "AnimatedButtonMenu", "class_animated_button_menu.html", null ],
      [ "AutoCameraToggleController", "class_auto_camera_toggle_controller.html", null ],
      [ "AutomaticMovementController", "class_automatic_movement_controller.html", null ],
      [ "Ayuda", "class_ayuda.html", null ],
      [ "BotonNavegacion", "class_boton_navegacion.html", null ],
      [ "BtnScrollHide", "class_btn_scroll_hide.html", null ],
      [ "ButtonHoverEffect", "class_button_hover_effect.html", null ],
      [ "CameraView", "class_camera_view.html", null ],
      [ "CanvasTextSelected", "class_canvas_text_selected.html", null ],
      [ "CursorChanger", "class_cursor_changer.html", null ],
      [ "CursorChangerMenu", "class_cursor_changer_menu.html", null ],
      [ "DefaultCursorSetter", "class_default_cursor_setter.html", null ],
      [ "DelayedFadeInButtons", "class_delayed_fade_in_buttons.html", null ],
      [ "DotsPattern", "class_dots_pattern.html", null ],
      [ "FastScrollRect", "class_fast_scroll_rect.html", null ],
      [ "GradientBackground", "class_gradient_background.html", null ],
      [ "HoverTextDisplay", "class_hover_text_display.html", null ],
      [ "InputController", "class_input_controller.html", [
        [ "MouseController", "class_mouse_controller.html", null ]
      ] ],
      [ "KeyboardController", "class_keyboard_controller.html", null ],
      [ "LinkHandler", "class_link_handler.html", null ],
      [ "LinkOpener", "class_link_opener.html", null ],
      [ "MainScript", "class_main_script.html", null ],
      [ "MainTextSelected", "class_main_text_selected.html", null ],
      [ "MaterialTransition", "class_material_transition.html", null ],
      [ "MobileController", "class_mobile_controller.html", null ],
      [ "MostrarImagenDesdeBoton", "class_mostrar_imagen_desde_boton.html", null ],
      [ "MostrarSliderSonido", "class_mostrar_slider_sonido.html", null ],
      [ "MostrarTextoDesdeBoton", "class_mostrar_texto_desde_boton.html", null ],
      [ "MostrarVideoDesdeBotonConSubtitulos", "class_mostrar_video_desde_boton_con_subtitulos.html", null ],
      [ "OrientationAdapter", "class_orientation_adapter.html", null ],
      [ "PanelImagenController", "class_panel_imagen_controller.html", null ],
      [ "PanelTextoController", "class_panel_texto_controller.html", null ],
      [ "PanelVideoControllerConSubtitulos", "class_panel_video_controller_con_subtitulos.html", null ],
      [ "RotationNotifier", "class_rotation_notifier.html", null ],
      [ "Rotator", "class_rotator.html", null ],
      [ "SceneControllers", "class_scene_controllers.html", null ],
      [ "SceneLoader", "class_scene_loader.html", null ],
      [ "ScrollCreditos", "class_scroll_creditos.html", null ],
      [ "ShowGaleryAndroid", "class_show_galery_android.html", null ],
      [ "ShowHandle", "class_show_handle.html", null ],
      [ "ShowSelectedPosition", "class_show_selected_position.html", null ],
      [ "SimpleButtonHover", "class_simple_button_hover.html", null ],
      [ "SkyBoxButtonSelected", "class_sky_box_button_selected.html", null ],
      [ "SoundController", "class_sound_controller.html", null ],
      [ "StartController", "class_start_controller.html", null ],
      [ "StopMovementPanel", "class_stop_movement_panel.html", null ],
      [ "StopZoom", "class_stop_zoom.html", null ],
      [ "SwipeMenu", "class_swipe_menu.html", null ],
      [ "TMP_LinkOpener", "class_t_m_p___link_opener.html", null ],
      [ "TransitionScrollBar", "class_transition_scroll_bar.html", null ],
      [ "TypewriterEffect", "class_typewriter_effect.html", null ],
      [ "VolverAMain360", "class_volver_a_main360.html", null ],
      [ "ZoomController", "class_zoom_controller.html", null ]
    ] ],
    [ "AnimatedButton.VibrationSettings", "class_animated_button_1_1_vibration_settings.html", null ]
];